// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/interview-home/Clean.tsx": () => import("../components/mockups/interview-home/Clean.tsx"),
  "./components/mockups/interview-home/DarkPremium.tsx": () => import("../components/mockups/interview-home/DarkPremium.tsx"),
  "./components/mockups/interview-home/Vibrant.tsx": () => import("../components/mockups/interview-home/Vibrant.tsx")
};
